### ISSUE TITLE
Implement Router to support front-end

### ISSUE THREAD

**Issue by chenzhutian** [HKUST-VISLab/vismooc-web-server#16]
- read document of [koa router](https://github.com/alexmingoia/koa-router)
- specific the routers we need
- refine the data format we need for frontend

**Comment by chenzhutian** [comment]
The routes we need:

- [ ] 1. get -> `'/getContentBasedData?type=action&courseId=' + courseId + '&videoId=' + videoId;`  
- [ ] 2. get -> `'/getContentBasedData?type=seek&courseId=' + courseId + '&videoId=' + videoId;`  
- [ ] 3.get -> `'/getCourseList'`
- [ ] 4.  get ->  `'/getVideoList?courseId=' + courseId;`
- [ ] 5.  get -> `'/getCourseInfo?courseId=' + courseId;`
- [ ] 7.  get -> `'/getHotness?courseId=' + courseId;`
- [ ] 8.  get -> `'/getDemographicData?courseId=' + courseId;`
- [ ] 9.  get -> `'/getVideoPop?courseId=' + courseId + '&videoId=' + videoId;`

**Comment by chenzhutian** [comment]
Reference here
https://github.com/HKUST-VISLab/vismooc-front-end/blob/master/src/service/datamanager.js#L8-L86

**Comment by chenzhutian** [comment]
After [this issue](https://github.com/HKUST-VISLab/vismooc-data-server/issues/39) is fixed, sync to the newest, true, right data schema

**Comment by wdan** [comment]
Fake the unexisted data (like country)
