### ISSUE TITLE
Oauth2

### ISSUE THREAD

**Issue by chenzhutian** [HKUST-VISLab/vismooc-web-server#5]
Oauth2 protocol need to be supported

**Comment by wdan** [comment]
Send mails to ask for the OAuth2 tokens:

"1. The OAuth2 application registration is performed by system administrator. It should come with the URL/ IP address. The server should incorporate with server certificate. For testing, you may prepare a self-signed certificate and then allow us to trust your certificate. You may discuss with Ben for further technical details."
