### ISSUE TITLE
Unit test: 80%

### ISSUE THREAD

**Issue by wdan** [HKUST-VISLab/vismooc-web-server#64]
Due: May 9

**Comment by chenzhutian** [comment]
@Nehzilrz 
https://github.com/HKUST-VISLab/vismooc-web-server/commit/dd3fe109328f7bc1afc1b901475a1a635561165a

看一下这个commit的一些comment，然后把需要修改的改了吧

**Comment by Nehzilrz** [comment]
ok

**Comment by chenzhutian** [comment]
for @Nehzilrz 
1. database
2. controller
3. router
